Repository Newgnal/Backend, pull requests merged in 2025-07, with the labels that each got.

#64 bug: healthCheck 버그 해결
  src/main/java/com/tave/alarmissue/news/domain/News.java
  src/main/resources/application.yml
Labels: 🐞 Bug

#72 fix: 크롤링 시간 변경
  src/main/java/com/tave/alarmissue/news/service/DaumNewsCrawlService.java
  src/main/java/com/tave/alarmissue/news/service/NaverNewsCrawlService.java
Labels: ✨ feature

#59 feat: 뉴스 댓글 삭제 기능 구현
  src/main/java/com/tave/alarmissue/news/controller/NewsCommentController.java
  src/main/java/com/tave/alarmissue/news/converter/NewsCommentConverter.java
  src/main/java/com/tave/alarmissue/news/dto/request/NewsCommentRequestDto.java
  src/main/java/com/tave/alarmissue/news/exceptions/NewsCommentErrorCode.java
  src/main/java/com/tave/alarmissue/news/repository/NewsCommentRepository.java
  src/main/java/com/tave/alarmissue/news/service/NewsCommentService.java
Labels: ✨ feature

#61 feat: 뉴스 댓글 수정 기능 구현
  src/main/java/com/tave/alarmissue/news/controller/NewsCommentController.java
  src/main/java/com/tave/alarmissue/news/domain/NewsComment.java
  src/main/java/com/tave/alarmissue/news/service/NewsCommentService.java
Labels: ✨ feature

#78 feat: 문의 기능 구현
  src/main/java/com/tave/alarmissue/inquiry/controller/InquiryController.java
  src/main/java/com/tave/alarmissue/inquiry/converter/InquiryConverter.java
  src/main/java/com/tave/alarmissue/inquiry/domain/Inquiry.java
  src/main/java/com/tave/alarmissue/inquiry/dto/request/InquiryRequest.java
  src/main/java/com/tave/alarmissue/inquiry/dto/response/InquiryResponse.java
  src/main/java/com/tave/alarmissue/inquiry/repository/InquiryRepository.java
  src/main/java/com/tave/alarmissue/inquiry/service/InquiryService.java
  src/main/java/com/tave/alarmissue/news/converter/NewsVoteConverter.java
Labels: ✨ feature

#80 feat: 게시글 조회 기능 추가
  src/main/java/com/tave/alarmissue/inquiry/controller/InquiryController.java
  src/main/java/com/tave/alarmissue/post/controller/CommentController.java
  src/main/java/com/tave/alarmissue/post/controller/LikeController.java
  src/main/java/com/tave/alarmissue/post/controller/PostController.java
  src/main/java/com/tave/alarmissue/post/controller/PostLIstController.java
  src/main/java/com/tave/alarmissue/post/controller/ReportController.java
  src/main/java/com/tave/alarmissue/post/controller/VoteController.java
  src/main/java/com/tave/alarmissue/post/converter/PostCommentConverter.java
  src/main/java/com/tave/alarmissue/post/converter/PostConverter.java
  src/main/java/com/tave/alarmissue/post/converter/PostReplyConverter.java
  src/main/java/com/tave/alarmissue/post/domain/Post.java
  src/main/java/com/tave/alarmissue/post/domain/PostComment.java
  src/main/java/com/tave/alarmissue/post/domain/enums/SortType.java
  src/main/java/com/tave/alarmissue/post/dto/response/CommentResponse.java
  src/main/java/com/tave/alarmissue/post/dto/response/HotPostResponse.java
  src/main/java/com/tave/alarmissue/post/dto/response/PageResponse.java
  src/main/java/com/tave/alarmissue/post/dto/response/PostDetailResponse.java
  src/main/java/com/tave/alarmissue/post/dto/response/PostHomeResponse.java
  src/main/java/com/tave/alarmissue/post/dto/response/PostResponse.java
  src/main/java/com/tave/alarmissue/post/dto/response/ThemeCountResponse.java
  src/main/java/com/tave/alarmissue/post/repository/CommentRepository.java
  src/main/java/com/tave/alarmissue/post/repository/PostRepository.java
  src/main/java/com/tave/alarmissue/post/repository/ReplyRepository.java
  src/main/java/com/tave/alarmissue/post/service/CommentService.java
  src/main/java/com/tave/alarmissue/post/service/PostListService.java
  src/main/java/com/tave/alarmissue/post/service/PostService.java
  src/main/java/com/tave/alarmissue/search/controller/SearchController.java
  src/main/java/com/tave/alarmissue/security/config/SecurityConfig.java
  src/main/java/com/tave/alarmissue/user/controller/UserController.java
Labels: ✨ feature

#82 fix: 게시글,댓글,대댓글 삭제 시 신고 삭제
  src/main/java/com/tave/alarmissue/post/domain/Post.java
  src/main/java/com/tave/alarmissue/post/domain/PostComment.java
  src/main/java/com/tave/alarmissue/post/domain/PostReply.java
Labels: 🐞 Bug

#88 feat: 뉴스 본문 S3 버킷에 저장
  build.gradle
  src/main/java/com/tave/alarmissue/AlarmissueApplication.java
  src/main/java/com/tave/alarmissue/global/config/S3Config.java
  src/main/java/com/tave/alarmissue/news/converter/NewsConverter.java
  src/main/java/com/tave/alarmissue/news/domain/News.java
  src/main/java/com/tave/alarmissue/news/dto/response/NewsDetailResponseDto.java
  src/main/java/com/tave/alarmissue/news/exceptions/NewsErrorCode.java
  src/main/java/com/tave/alarmissue/news/service/crawl/DaumNewsCrawlService.java
  src/main/java/com/tave/alarmissue/news/service/crawl/NaverNewsCrawlService.java
  src/main/java/com/tave/alarmissue/news/service/crawl/S3Uploader.java
  src/main/resources/application.yml
Labels: ✨ feature

#95 fix: 검색 슬라이싱 추가
  src/main/java/com/tave/alarmissue/news/repository/NewsRepository.java
  src/main/java/com/tave/alarmissue/search/controller/SearchController.java
  src/main/java/com/tave/alarmissue/search/dto/SearchResultResponse.java
  src/main/java/com/tave/alarmissue/search/service/SearchService.java
Labels: 🛠️fix

#90 fix: 뉴스 조회 시 댓글 수 반영 & view,voteNumm DB에 update
  src/main/java/com/tave/alarmissue/news/controller/NewsVoteController.java
  src/main/java/com/tave/alarmissue/news/converter/NewsConverter.java
  src/main/java/com/tave/alarmissue/news/domain/News.java
  src/main/java/com/tave/alarmissue/news/service/NewsService.java
  src/main/java/com/tave/alarmissue/news/service/NewsVoteService.java
Labels: 🛠️fix

#93 fix: 조회수 순 뉴스 정렬 수정
  src/main/java/com/tave/alarmissue/news/repository/NewsRepository.java
  src/main/java/com/tave/alarmissue/news/service/NewsService.java
Labels: 🛠️fix

#99 fix: news softDelete + Post dto 수정
  src/main/java/com/tave/alarmissue/news/domain/News.java
  src/main/java/com/tave/alarmissue/news/repository/NewsRepository.java
  src/main/java/com/tave/alarmissue/news/service/NewsDeleteService.java
  src/main/java/com/tave/alarmissue/post/converter/PostConverter.java
  src/main/java/com/tave/alarmissue/post/domain/Post.java
  src/main/java/com/tave/alarmissue/post/dto/request/PostCreateRequest.java
  src/main/java/com/tave/alarmissue/post/dto/request/PostUpdateRequest.java
  src/main/java/com/tave/alarmissue/post/dto/response/PostResponse.java
  src/main/java/com/tave/alarmissue/post/exception/PostErrorCode.java
  src/main/java/com/tave/alarmissue/post/service/PostService.java
Labels: 🛠️fix

#87 feat: 뉴스 대댓글 작성/삭제/수정/조회 기능 구현
  src/main/java/com/tave/alarmissue/news/controller/NewsCommentController.java
  src/main/java/com/tave/alarmissue/news/controller/NewsController.java
  src/main/java/com/tave/alarmissue/news/controller/NewsDetailController.java
  src/main/java/com/tave/alarmissue/news/controller/NewsVoteController.java
  src/main/java/com/tave/alarmissue/news/converter/NewsCommentConverter.java
  src/main/java/com/tave/alarmissue/news/domain/News.java
  src/main/java/com/tave/alarmissue/news/domain/NewsComment.java
  src/main/java/com/tave/alarmissue/news/dto/request/NewsCommentUpdateRequest.java
  src/main/java/com/tave/alarmissue/news/dto/request/NewsReplyRequest.java
  src/main/java/com/tave/alarmissue/news/dto/request/NewsSortType.java
  src/main/java/com/tave/alarmissue/news/dto/request/enums/NewsSortType.java
  src/main/java/com/tave/alarmissue/news/dto/response/NewsCommentResponseDto.java
  src/main/java/com/tave/alarmissue/news/exceptions/NewsErrorCode.java
  src/main/java/com/tave/alarmissue/news/exceptions/NewsException.java
  src/main/java/com/tave/alarmissue/news/repository/NewsCommentRepository.java
  src/main/java/com/tave/alarmissue/news/service/NewsCommentService.java
  src/main/java/com/tave/alarmissue/news/service/NewsService.java
Labels: ✨ feature

#101 feat: newVote 댓글에 반영
  src/main/java/com/tave/alarmissue/news/controller/NewsCommentController.java
  src/main/java/com/tave/alarmissue/news/converter/NewsCommentConverter.java
  src/main/java/com/tave/alarmissue/news/repository/NewsCommentRepository.java
  src/main/java/com/tave/alarmissue/news/repository/NewsVoteRepository.java
  src/main/java/com/tave/alarmissue/news/service/NewsCommentService.java
  src/main/java/com/tave/alarmissue/news/service/NewsVoteService.java
Labels: ✨ feature, 🛠️fix

#110 bug: build.gradle 수정
  build.gradle
Labels: bug
